branch-defaults:
  master:
    environment: terminBucher-4pa9e-env
    group_suffix: null
global:
  application_name: termin-bucher
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 17.12.0-ce
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
