branch-defaults:
  master:
    environment: master-termin-bucher
    group_suffix: null
environment-defaults:
  master-termin-bucher:
    branch: null
    repository: null
global:
  application_name: termin-bucher
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 17.12.0-ce
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
