apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminator-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: terminator-api
          imagePullPolicy: Always
          image: registry.digitalocean.com/unmanaged-registry/terminator-api:latest
          # command: ["node"]
          # args:
          #   - "index.js"
          ports:
            - containerPort: 80
          env:
            - name: "ENV"
              value: "PROD"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
  name: terminator-api-ingress
spec:
  rules:
    - host: terminator.dev.hobby-paas.cf
      http:
        paths:
         - path: /api/*
           backend:
              serviceName: terminator-api
              servicePort: http            
---
apiVersion: v1
kind: Service
metadata:
  name: terminator-api
spec:
  ports:
    - name: http
      port: 8002
      targetPort: 3000
  selector:
    app: terminator-api
  type: NodePort
