apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminator-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: terminator-api
          imagePullPolicy: Always
          image: registry.digitalocean.com/unmanaged-registry/terminator-api:latest
          # command: ["node"]
          # args:
          #   - "index.js"
          ports:
            - containerPort: 80
          env:
            - name: "ENV"
              value: "PROD"