name: Build and Deploy to digital ocean

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  registry: unmanaged-registry
  GKE_EMAIL: 255561906071-compute@developer.gserviceaccount.com
  GITHUB_SHA: ${{ github.sha }}
  app: terminator-api

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.do_token}}
      
      - name: login to registry
        run: doctl registry login 
                
      - name: Build
        run: docker build -t registry.digitalocean.com/$registry/$app:latest -t registry.digitalocean.com/$registry/$app:$GITHUB_SHA .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: | 
            docker push --all-tags registry.digitalocean.com/$registry/$app

      # Set up kustomize
      - name: Set up Kustomize
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save unmanaged-cluster

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          cd k8s_config
          kubectl apply -k .
          kubectl set image deployment/$app $app=registry.digitalocean.com/$registry/$app:$GITHUB_SHA --record 

      - name: Verify deployment
        run:  | 
          kubectl rollout status deployment/$app --namespace $namespace
